### ISSUE TITLE
Enhancements If possible 

### ISSUE THREAD

**Issue by CursedPop** [beCoditive/Max-Bot#21]
- Weather Command
- Urban Dictionary Command
- Private Voice Channel Command
- Advanced Application Command (user fills out a form for mod etc)
- Snipe Command
- Auto Role Command
- Nuke Command (if needed)

**Comment by Max2408** [comment]
Yeah Auto Roles is already there

**Comment by CursedPop** [comment]
Oh sweet didn't notice that

**Comment by Max2408** [comment]
And I can't give nuke command as it is against Discord Terms  and Conditions

**Comment by Max2408** [comment]
I will try my best to make all other commands

**Comment by CursedPop** [comment]
Yeah kinda figured the nuke command wouldn't be allowed but figured to ask anyway and okay man appreciate it

**Comment by CursedPop** [comment]
Hey just want to say I found an Urban and snipe one but not sure what to do with them now(add them to the bot)

**Comment by Max2408** [comment]
bro sorry but I made them yesterday

**Comment by CursedPop** [comment]
oh okay no biggie
