### ISSUE TITLE
Music Not playing

### ISSUE THREAD

**Issue by CursedPop** [beCoditive/Max-Bot#27]
Not exactly sure what's happening but when I try to play music it doesn't. Like the bot joins the channel and I see the green ring around it like it's "playing" something, but it's not playing the music.

**Comment by Max2408** [comment]
you have to give a link to the music it only supports yt 😂. Example :
$play https://youtu.be/h5WN3pkxPF0

**Comment by CursedPop** [comment]
Just tried what you posted and it still isn't working.. it joins and shows the green ring around it but no sound...

**Comment by Max2408** [comment]
ohh
i will try to fix it

**Comment by CursedPop** [comment]
Okay sounds good!
